version: '3.9'
services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 112233
      POSTGRES_DB: household
