version: '3.9'
services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 112233
      POSTGRES_DB: household
  redis:
    image: redis/redis-stack:7.4.0-v0
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - '8001:8001'
    depends_on:
      - redis
