import { config } from 'dotenv';

config();

export const env = {
  SALT_PASSWORD: Number(process.env.SALT_PASSWORD),
  APP_ID_ZALO: process.env.APP_ID_ZALO,
  SECRET_KEY_ZALO: process.env.SECRET_KEY_ZALO,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URL: process.env.GOOGLE_REDIRECT_URL,
  JWT_ACCESS_TOKEN_EXPIRE_IN_SECONDS: 10, // Number(process.env.JWT_ACCESS_TOKEN_EXPIRE_IN_MINUTES) * 60,
  JWT_REFRESH_TOKEN_EXPIRE_IN_SECONDS: Number(process.env.JWT_REFRESH_TOKEN_EXPIRE_IN_DAY) * 24 * 60 * 60,
  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,
  COOKIE_REFRESH_TOKEN_EXPIRE: Number(process.env.COOKIE_REFRESH_TOKEN_EXPIRE_DAY) * 24 * 60 * 60 * 1000,
};
